cat("=====================================\n")
cat(" Running Greeks Correlation Project \n")
cat("=====================================\n\n")

source("scripts/01_download_data.R")
source("scripts/02_prepare_returns.R")
source("scripts/03_model_setup.R")
source("scripts/04_price_surfaces.R")
source("scripts/05_delta_gamma.R")
source("scripts/06_theta.R")
source("scripts/07_vega.R")
source("scripts/08_visualization.R")

cat("\n=====================================\n")
cat(" Project completed successfully\n")
cat("=====================================\n")